
import email.standardOperation;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.ConnectionProvider;
import project.InsertUpdateDelete;
import project.createDB;
import project.select;
import project.tables;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import java.util.Calendar;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author daviddaillere
 */
public class SignUp extends javax.swing.JFrame {

    private String dbName;

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel13.requestFocus();
        jLabel14.setVisible(false);
        jLabel11.setVisible(false);
    }

    private void saveSignUp() {

        // TODO add your handling code here:
        String name = nameTxt.getText().replaceAll("\\s", "");
        String email = emailTxt.getText();
        String password = passwordTxt.getText();
        String question = (String) questionBox.getSelectedItem();
        String answer = answerTxt.getText();
        String address = addressTxt.getText();
        SimpleDateFormat dtf = new SimpleDateFormat("MM/dd/yyyy");
        Calendar calendar = Calendar.getInstance();
        Date dateObj = calendar.getTime();
        String startDate = dtf.format(dateObj);

        dbName = nameTxt.getText().replaceAll("\\s", "");
        int checkEmail = 0;
        int checkID = 0;

        if (name.equals("") || email.equals("") || password.equals("") || answer.equals("") || address.equals("")) {
            JOptionPane.showMessageDialog(null, "veuillez remplir toutes les informations");
        } else {

            createDB.newDB("admin_database");
            tables.createUsersTable();
            ResultSet rs = select.getData("admin_database", "select * from users where email = '" + email + "'");
            ResultSet rs2 = select.getData("admin_database", "select * from users where name = '" + name + "'");
            try {
                if (rs.next()) {
                    checkEmail = 1;

                }
                if (rs2.next()) {
                    checkID = 1;
                }
                rs.close();
                rs2.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            if ((checkEmail == 0 && checkID == 0)) {
                new Thread(new Runnable() {
                    public void run() {
                        //Do whatever
                        standardOperation.newUser(emailTxt.getText());
                    }
                }).start();

                String Query;
                Query = "insert into users values('" + name + "','" + email + "','" + password + "','" + question + "','" + answer + "','" + address + "','trial','" + startDate + "')";
                InsertUpdateDelete.setData("admin_database", Query, "enregistré avec succès");

                createDB.newDB(dbName);
                tables.createTables(dbName);

                setVisible(false);
                new SignUp().setVisible(false);
                new Simply().setVisible(true);
            } else {
                if (checkEmail == 1 && checkID == 1) {
                    JOptionPane.showMessageDialog(null, "Hmm! Il Semblerait Que Ton Compte Existe Deja (essaie: mot de passe oublié ou contact admin");
                } else {
                    if (checkEmail == 1 && checkID == 0) {
                        JOptionPane.showMessageDialog(null, "Oups! Ton Adresse Email Est Déja Utilisée (conseil: essaie mot de passe oublié)  ");
                    }
                    if (checkID == 1 && checkEmail == 0) {
                        JOptionPane.showMessageDialog(null, "Oups,  Identifiant Non Disponible");
                    }
                }

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        answerTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        questionBox = new javax.swing.JComboBox<>();
        addressTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inscription");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("identifiant");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mot de Passe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, 20));

        jLabel5.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Question de securité");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, 20));

        jLabel6.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Réponse");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, 20));

        jLabel7.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Adresse");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, 20));

        nameTxt.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 290, -1));

        emailTxt.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(102, 102, 102));
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 290, -1));

        answerTxt.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        answerTxt.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(answerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 290, -1));

        jLabel8.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, 20));

        passwordTxt.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 290, -1));

        questionBox.setBackground(new java.awt.Color(255, 255, 255));
        questionBox.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        questionBox.setForeground(new java.awt.Color(102, 102, 102));
        questionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quel est ta ville de naisance ? ", "Nom de ton premier animal ?", "Quel est ton Acteur préféré?", " " }));
        getContentPane().add(questionBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 290, -1));

        addressTxt.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        addressTxt.setForeground(new java.awt.Color(102, 102, 102));
        addressTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressTxtFocusLost(evt);
            }
        });
        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        getContentPane().add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 290, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("_________");
        jLabel11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel11FocusGained(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 120, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("___________");
        jLabel14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel14FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabel14FocusLost(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 120, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_2.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Connexion");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Inscription");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jLabel13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel13KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background1_1.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Êtes-Vous Sûre De Vouloir Fermer l'Application ?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        saveSignUp();
//    // TODO add your handling code here:
//        String name= nameTxt.getText().replaceAll("\\s", "");
//        String email= emailTxt.getText();
//        String password= passwordTxt.getText();
//        String question= (String)questionBox.getSelectedItem();
//        String answer= answerTxt.getText();
//        String address= addressTxt.getText();
//        SimpleDateFormat dtf = new SimpleDateFormat("MM/dd/yyyy");
//        Calendar calendar = Calendar.getInstance();
//        Date dateObj = calendar.getTime();
//        String startDate = dtf.format(dateObj); 
//  
//        
//        dbName= nameTxt.getText().replaceAll("\\s", "");
//        int checkEmail= 0;
//        int checkID=0;
//        
//        if(name.equals("") || email.equals("")|| password.equals("")||answer.equals("")|| address.equals("")){
//            JOptionPane.showMessageDialog(null, "veuillez remplir toutes les informations");
//        }
//
//        else{
//  
//            createDB.newDB("admin_database");
//            tables.createUsersTable();
//            ResultSet rs= select.getData("admin_database","select * from users where email = '"+email+"'");
//            ResultSet rs2= select.getData("admin_database","select * from users where name = '"+name+"'");
//            try{
//                if(rs.next())  {
//                 checkEmail=1;
//                
//                }
//                if(rs2.next()){
//                 checkID=1;
//                }
//                 rs.close();
//                 rs2.close();
//            } 
//            
//            catch(Exception e){
//                 JOptionPane.showMessageDialog(null, e);
//            }
//            
//            if ((checkEmail==0 && checkID==0)){
//            String Query;
//            Query = "insert into users values('"+name+"','"+email+"','"+password+"','"+question+"','"+answer+"','"+address+"','trial','"+startDate+"')";
//            InsertUpdateDelete.setData("admin_database",Query, "enregistré avec succès");           
//            
//            createDB.newDB(dbName);
//            tables.createTables(dbName);
//
//        File file = new File("documents");
//        if (!file.exists()) {
//            if (file.mkdir()) {
//                System.out.println("Directory is created!");
//            } else {
//                System.out.println("Failed to create directory!");
//            }
//        }
//        //To create multiple directories/folders
//        File files = new File("documents/"+dbName+"/contrat");
//        if (!files.exists()) {
//            if (files.mkdirs()) {
//                System.out.println("Multiple directories are created!");
//            } else {
//                System.out.println("Failed to create multiple directories!");
//            }
//        }
//        
//         files = new File("documents/"+dbName+"/facture");
//        if (!files.exists()) {
//            if (files.mkdirs()) {
//                System.out.println("Multiple directories are created!");
//            } else {
//                System.out.println("Failed to create multiple directories!");
//            }
//        }
//          files = new File("documents/"+dbName+"/image");
//        if (!files.exists()) {
//            if (files.mkdirs()) {
//                System.out.println("Multiple directories are created!");
//            } else {
//                System.out.println("Failed to create multiple directories!");
//            }
//        }
//
//                files = new File("documents/" + dbName + "/image");
//                if (!files.exists()) {
//                    if (files.mkdirs()) {
//                        System.out.println("Multiple directories are created!");
//                    } else {
//                        System.out.println("Failed to create multiple directories!");
//                    }
//                }
//                files = new File("documents/" + dbName + "/enveloppe");
//                if (!files.exists()) {
//                    if (files.mkdirs()) {
//                        System.out.println("Multiple directories are created!");
//                    } else {
//                        System.out.println("Failed to create multiple directories!");
//                    }
//                }
//
//            setVisible(false);
//            new SignUp().setVisible(false);
//            new Simply().setVisible(true);      
//            }
//             
//            else{
//                if (checkEmail==1 && checkID== 1){
//                    JOptionPane.showMessageDialog(null, "Hmm! Il Semblerait Que Ton Compte Existe Deja (essaie: mot de passe oublié ou contact admin");
//                }
//                 else{
//                if(checkEmail==1 && checkID==0){      
//                   JOptionPane.showMessageDialog(null, "Oups! Ton Adresse Email Est Déja Utilisée (conseil: essaie mot de passe oublié)  "); 
//                }
//                if (checkID==1 && checkEmail==0){
//                   JOptionPane.showMessageDialog(null, "Oups,  Identifiant Non Disponible"); 
//                }
//                 }
//               
//                
//            }
//            
//        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        setVisible(false);
        new Simply().setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel11FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11FocusGained

    private void jLabel14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel14FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14FocusGained

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void addressTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTxtFocusLost
        jLabel13.requestFocus();
        jLabel14.setVisible(true);
        jLabel11.setVisible(false);
    }//GEN-LAST:event_addressTxtFocusLost

    private void jLabel14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel14FocusLost
        jLabel12.requestFocus();
        jLabel11.setVisible(true);
        jLabel14.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14FocusLost

    private void jLabel13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel13KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            saveSignUp();
        }
    }//GEN-LAST:event_jLabel13KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField answerTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JComboBox<String> questionBox;
    // End of variables declaration//GEN-END:variables
}
